{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: {{ include "fusionauth.PodDisruptionBudget" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "fusionauth.fullname" . }}
spec:
  maxUnavailable: {{ sub .Values.replicaCount 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fusionauth.name" . }}
{{- end }}