{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fusionauth.serviceAccountName" . }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
{{ .Values.serviceAccount.annotations | toYaml | indent 4 }}
  {{- end }}
{{- end }}
